-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_CompanySettings" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 1,
    "companyName" TEXT NOT NULL DEFAULT '',
    "addressLine" TEXT NOT NULL DEFAULT '',
    "postalCode" TEXT NOT NULL DEFAULT '',
    "city" TEXT NOT NULL DEFAULT '',
    "country" TEXT NOT NULL DEFAULT 'DE',
    "vatId" TEXT NOT NULL DEFAULT '',
    "taxNumber" TEXT NOT NULL DEFAULT '',
    "ownerName" TEXT NOT NULL DEFAULT '',
    "accentColor" TEXT NOT NULL DEFAULT '#2E2B2A',
    "email" TEXT NOT NULL DEFAULT '',
    "phone" TEXT NOT NULL DEFAULT '',
    "website" TEXT NOT NULL DEFAULT '',
    "logoPath" TEXT NOT NULL DEFAULT '',
    "bankName" TEXT NOT NULL DEFAULT '',
    "iban" TEXT NOT NULL DEFAULT '',
    "bic" TEXT NOT NULL DEFAULT '',
    "accountHolder" TEXT NOT NULL DEFAULT '',
    "invoiceNumberPrefix" TEXT NOT NULL DEFAULT 'RE-',
    "invoiceNumberNext" INTEGER NOT NULL DEFAULT 1,
    "invoiceNumberPadding" INTEGER NOT NULL DEFAULT 4,
    "quoteNumberPrefix" TEXT NOT NULL DEFAULT 'AN-',
    "quoteNumberNext" INTEGER NOT NULL DEFAULT 1,
    "quoteNumberPadding" INTEGER NOT NULL DEFAULT 4,
    "creditNumberPrefix" TEXT NOT NULL DEFAULT 'GS-',
    "creditNumberNext" INTEGER NOT NULL DEFAULT 1,
    "creditNumberPadding" INTEGER NOT NULL DEFAULT 4,
    "currency" TEXT NOT NULL DEFAULT 'EUR',
    "locale" TEXT NOT NULL DEFAULT 'de-DE',
    "defaultTaxRate" REAL NOT NULL DEFAULT 19,
    "taxRegime" TEXT NOT NULL DEFAULT 'standard',
    "paymentTermDays" INTEGER NOT NULL DEFAULT 14,
    "defaultTerms" TEXT NOT NULL DEFAULT '',
    "defaultFooter" TEXT NOT NULL DEFAULT '',
    "defaultNotes" TEXT NOT NULL DEFAULT '',
    "eInvoiceFormat" TEXT NOT NULL DEFAULT 'off',
    "buyerReference" TEXT NOT NULL DEFAULT '',
    "showEpcQr" BOOLEAN NOT NULL DEFAULT true,
    "smtpHost" TEXT NOT NULL DEFAULT '',
    "smtpPort" INTEGER NOT NULL DEFAULT 587,
    "smtpSecure" BOOLEAN NOT NULL DEFAULT false,
    "smtpUser" TEXT NOT NULL DEFAULT '',
    "smtpPasswordEnc" TEXT NOT NULL DEFAULT '',
    "mailFromName" TEXT NOT NULL DEFAULT '',
    "mailFromEmail" TEXT NOT NULL DEFAULT '',
    "mailReplyTo" TEXT NOT NULL DEFAULT '',
    "mailBcc" TEXT NOT NULL DEFAULT '',
    "mailEnabled" BOOLEAN NOT NULL DEFAULT false,
    "mailSendTime" TEXT NOT NULL DEFAULT '09:00',
    "mailSubject" TEXT NOT NULL DEFAULT 'Rechnung {nummer}',
    "mailBody" TEXT NOT NULL DEFAULT '',
    "mailAttachment" TEXT NOT NULL DEFAULT 'pdf',
    "updatedAt" DATETIME NOT NULL
);
INSERT INTO "new_CompanySettings" ("accentColor", "accountHolder", "addressLine", "bankName", "bic", "buyerReference", "city", "companyName", "country", "creditNumberNext", "creditNumberPadding", "creditNumberPrefix", "currency", "defaultFooter", "defaultNotes", "defaultTaxRate", "defaultTerms", "eInvoiceFormat", "email", "iban", "id", "invoiceNumberNext", "invoiceNumberPadding", "invoiceNumberPrefix", "locale", "logoPath", "ownerName", "paymentTermDays", "phone", "postalCode", "quoteNumberNext", "quoteNumberPadding", "quoteNumberPrefix", "showEpcQr", "taxNumber", "taxRegime", "updatedAt", "vatId", "website") SELECT "accentColor", "accountHolder", "addressLine", "bankName", "bic", "buyerReference", "city", "companyName", "country", "creditNumberNext", "creditNumberPadding", "creditNumberPrefix", "currency", "defaultFooter", "defaultNotes", "defaultTaxRate", "defaultTerms", "eInvoiceFormat", "email", "iban", "id", "invoiceNumberNext", "invoiceNumberPadding", "invoiceNumberPrefix", "locale", "logoPath", "ownerName", "paymentTermDays", "phone", "postalCode", "quoteNumberNext", "quoteNumberPadding", "quoteNumberPrefix", "showEpcQr", "taxNumber", "taxRegime", "updatedAt", "vatId", "website" FROM "CompanySettings";
DROP TABLE "CompanySettings";
ALTER TABLE "new_CompanySettings" RENAME TO "CompanySettings";
CREATE TABLE "new_Invoice" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "number" TEXT NOT NULL,
    "clientId" INTEGER NOT NULL,
    "docType" TEXT NOT NULL DEFAULT 'invoice',
    "issueDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dueDate" DATETIME NOT NULL,
    "serviceDateFrom" DATETIME,
    "serviceDateTo" DATETIME,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "approvedAt" DATETIME,
    "mailedAt" DATETIME,
    "mailAttempts" INTEGER NOT NULL DEFAULT 0,
    "mailError" TEXT NOT NULL DEFAULT '',
    "sentAt" DATETIME,
    "taxRegime" TEXT NOT NULL DEFAULT 'standard',
    "creditForInvoiceId" INTEGER,
    "currency" TEXT NOT NULL DEFAULT 'EUR',
    "discountValue" REAL NOT NULL DEFAULT 0,
    "discountType" TEXT NOT NULL DEFAULT 'percent',
    "subtotal" REAL NOT NULL DEFAULT 0,
    "taxTotal" REAL NOT NULL DEFAULT 0,
    "total" REAL NOT NULL DEFAULT 0,
    "amountPaid" REAL NOT NULL DEFAULT 0,
    "notes" TEXT NOT NULL DEFAULT '',
    "terms" TEXT NOT NULL DEFAULT '',
    "footer" TEXT NOT NULL DEFAULT '',
    "recurringInvoiceId" INTEGER,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Invoice_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Invoice_recurringInvoiceId_fkey" FOREIGN KEY ("recurringInvoiceId") REFERENCES "RecurringInvoice" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_Invoice" ("amountPaid", "clientId", "createdAt", "creditForInvoiceId", "currency", "discountType", "discountValue", "docType", "dueDate", "footer", "id", "issueDate", "notes", "number", "recurringInvoiceId", "sentAt", "serviceDateFrom", "serviceDateTo", "status", "subtotal", "taxRegime", "taxTotal", "terms", "total", "updatedAt") SELECT "amountPaid", "clientId", "createdAt", "creditForInvoiceId", "currency", "discountType", "discountValue", "docType", "dueDate", "footer", "id", "issueDate", "notes", "number", "recurringInvoiceId", "sentAt", "serviceDateFrom", "serviceDateTo", "status", "subtotal", "taxRegime", "taxTotal", "terms", "total", "updatedAt" FROM "Invoice";
DROP TABLE "Invoice";
ALTER TABLE "new_Invoice" RENAME TO "Invoice";
CREATE UNIQUE INDEX "Invoice_number_key" ON "Invoice"("number");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
